name: Node CI
on:
  - push
  - pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 16.x
          - 18.x
          - 20.x
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Redrun
        run: bun i redrun -g --no-save
      - name: Install
        run: bun i --no-save
      - name: Bootstrap
        run: redrun bootstrap
      - name: Lint
        run: redrun lint
